language: elixir

cache:
  directories:
  - priv/plts
  - deps

elixir:
  - 1.9.4

otp_release:
  - 22.0

before_script:
  - epmd -daemon

script:
  - mix test --include distributed
  - travis_wait 30 mix dialyzer --halt-exit-status
