language: elixir

cache:
  directories:
  - priv/plts
  - deps

elixir:
  - 1.10.1

otp_release:
  - 22.0

script:
  - mix test
  - mix format --check-formatted
  - travis_wait 30 mix dialyzer --halt-exit-status
